<a href="https://colab.research.google.com/github/labib1910024/Python_basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np

In [5]:
# Creating array
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

array([1, 2, 3, 4, 5])

In [6]:
array1

array([1, 2, 3, 4, 5])

In [7]:
array2

array([ 6,  7,  8,  9, 10])

In [9]:
#  Creating arrays with zeros, ones, arange, and linspace
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ones_array = np.ones((3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arange_array = np.arange(0, 10, 2)
arange_array

array([0, 2, 4, 6, 8])

In [15]:
arange_array = np.arange(0, 10, 3)
arange_array

array([0, 3, 6, 9])

In [17]:
linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
linspace_array = np.linspace(0, 1, 10)
linspace_array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [21]:
add = array1 + array2
add

array([ 6,  8, 10, 12])

In [22]:
sub = array1 - array2
sub

array([-4, -4, -4, -4])

In [23]:
mul = array1 * array2
mul

array([ 5, 12, 21, 32])

In [24]:
div = array1 / array2
div

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [26]:
# Array indexing and slicing
array = np.array([1, 2, 3, 4, 5, 6])
first = array[0]
first

1

In [28]:
slice1 = array[1:4]
slice2 = array[:3]
slice3 = array[3:]

In [29]:
slice1

array([2, 3, 4])

In [30]:
slice2

array([1, 2, 3])

In [31]:
slice3

array([4, 5, 6])

In [32]:
# Array aggregation
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Aggregation operations
array_sum = np.sum(array)
array_mean = np.mean(array)
array_min = np.min(array)
array_max = np.max(array)

In [33]:
array_sum

45

In [34]:
array_mean

5.0

In [35]:
array_min

1

In [36]:
array_max

9

In [37]:
array_min

1