<a href="https://colab.research.google.com/github/labib1910024/Python_basic-Machine-Learning/blob/main/Numpy_W3School.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
arr = numpy.array([1,3,5,6])
print(arr)

[1 3 5 6]


In [2]:
import numpy as np
arr = np.array([1,3,5,6])
print(arr)

[1 3 5 6]


In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [4]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

2
