<a href="https://colab.research.google.com/github/labib1910024/Python_basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [4]:
import numpy as np

In [ ]:
# Creating array
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

In [ ]:
array1

array([1, 2, 3, 4, 5])

In [ ]:
array2

array([ 6,  7,  8,  9, 10])

In [ ]:
arr = np.array([[2,3,4],[2,5,6]])
arr

array([[2, 3, 4],
       [2, 5, 6]])

In [ ]:
arr[0][1]

3

In [ ]:
arr[0]

array([2, 3, 4])

In [ ]:
#  Creating arrays with zeros, ones, arange, and linspace
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros_array = np.zeros((3,10))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
zeros_array = np.zeros((3,2,4,10))
zeros_array

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [ ]:
ones_array = np.ones((3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.random.choice([2],size=(1,10))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
np.random.choice([2,5,8],size=(1,10))

array([[8, 2, 8, 8, 5, 8, 2, 2, 8, 2]])

In [ ]:
np.random.choice([2,5,8],size=(3,10))

array([[5, 8, 5, 5, 8, 8, 8, 5, 2, 8],
       [8, 5, 2, 8, 5, 5, 8, 5, 5, 2],
       [8, 5, 8, 2, 5, 8, 5, 8, 8, 8]])

In [ ]:
arr = np.random.choice([2,5,8],size=(3,5,4))
arr

array([[[8, 2, 8, 2],
        [5, 2, 8, 8],
        [2, 2, 5, 5],
        [8, 5, 2, 2],
        [5, 8, 2, 5]],

       [[8, 8, 5, 8],
        [2, 2, 5, 8],
        [5, 2, 8, 2],
        [8, 2, 2, 5],
        [2, 8, 5, 2]],

       [[2, 2, 5, 8],
        [2, 5, 2, 2],
        [2, 2, 8, 8],
        [8, 2, 8, 8],
        [2, 8, 2, 8]]])

In [ ]:
arr[1][2][2]

8

In [ ]:
arange_array = np.arange(0, 10, 2)
arange_array

array([0, 2, 4, 6, 8])

In [ ]:
arange_array = np.arange(0, 10, 3)
arange_array

array([0, 3, 6, 9])

In [ ]:
linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
linspace_array = np.linspace(0, 1, 10)
linspace_array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [ ]:
add = array1 + array2
add

array([ 6,  8, 10, 12])

In [ ]:
sub = array1 - array2
sub

array([-4, -4, -4, -4])

In [ ]:
mul = array1 * array2
mul

array([ 5, 12, 21, 32])

In [ ]:
div = array1 / array2
div

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
# Array indexing and slicing
array = np.array([1, 2, 3, 4, 5, 6])
first = array[0]
first

1

In [ ]:
slice1 = array[1:4]
slice2 = array[:3]
slice3 = array[3:]

In [ ]:
slice1

array([2, 3, 4])

In [ ]:
slice2

array([1, 2, 3])

In [ ]:
slice3

array([4, 5, 6])

In [ ]:
# Array aggregation
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Aggregation operations
array_sum = np.sum(array)
array_mean = np.mean(array)
array_min = np.min(array)
array_max = np.max(array)

In [ ]:
array_sum

45

In [ ]:
array_mean

5.0

In [ ]:
array_min

1

In [ ]:
array_max

9

In [ ]:
array_min

1

In [ ]:
arr = np.random.choice([2,5,8],size=(3,5,4))
arr

array([[[8, 8, 5, 5],
        [2, 8, 5, 2],
        [8, 8, 8, 5],
        [5, 5, 2, 5],
        [5, 5, 8, 2]],

       [[2, 5, 5, 8],
        [2, 8, 2, 5],
        [8, 5, 2, 8],
        [8, 2, 8, 5],
        [8, 5, 5, 5]],

       [[8, 5, 8, 2],
        [2, 8, 5, 2],
        [5, 2, 8, 8],
        [8, 5, 5, 2],
        [8, 5, 8, 8]]])

In [ ]:
arr[2]


array([[8, 5, 8, 2],
       [2, 8, 5, 2],
       [5, 2, 8, 8],
       [8, 5, 5, 2],
       [8, 5, 8, 8]])

In [ ]:
zeros_array = np.zeros((4,10))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
zeros_array.reshape(4,5,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
zeros_array.reshape(1,40,1)

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [ ]:
zeros_array.reshape(2,20,1)

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [ ]:
zeros_array = np.zeros((2,2))
zeros_array

array([[0., 0.],
       [0., 0.]])

In [ ]:
for i in zeros_array:
  print(i)

[0. 0.]
[0. 0.]


In [5]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
array3 = np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
array3.shape

(8,)

In [7]:
np.array_split(array3,2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [8]:
np.array_split(array3,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [10]:
arr3 = np.array([3,3,4,5,7,7,3,5,6,3])
arr3

array([3, 3, 4, 5, 7, 7, 3, 5, 6, 3])

In [11]:
np.where(arr3==7)

(array([4, 5]),)

In [12]:
np.where(arr3==3)

(array([0, 1, 6, 9]),)

In [13]:
np.sort(arr3)

array([3, 3, 3, 3, 4, 5, 5, 6, 7, 7])

In [17]:
arr4 = np.array([3,4,5,6,7])
x= [True,False,True,False,False]
new_arr = arr4[x]
new_arr

array([3, 5])

In [19]:
np.random.randint(100)

76